# GitHub Labels for Artomate Project
# This file defines all the labels used in the repository

labels:
  # Type labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "Something isn't valid"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"

  # Priority labels
  - name: "priority: high"
    color: "ff0000"
    description: "High priority issue"
  - name: "priority: medium"
    color: "ffa500"
    description: "Medium priority issue"
  - name: "priority: low"
    color: "ffff00"
    description: "Low priority issue"

  # Status labels
  - name: "status: blocked"
    color: "ff0000"
    description: "Issue is blocked by another issue"
  - name: "status: in progress"
    color: "0075ca"
    description: "Issue is being worked on"
  - name: "status: needs review"
    color: "ffa500"
    description: "Issue needs review"
  - name: "status: ready"
    color: "00ff00"
    description: "Issue is ready for work"

  # Component labels
  - name: "component: auth"
    color: "1d76db"
    description: "Authentication related"
  - name: "component: ui"
    color: "1d76db"
    description: "User interface related"
  - name: "component: api"
    color: "1d76db"
    description: "API related"
  - name: "component: database"
    color: "1d76db"
    description: "Database related"
  - name: "component: payment"
    color: "1d76db"
    description: "Payment processing related"
  - name: "component: ai"
    color: "1d76db"
    description: "AI/ML related"

  # Special labels
  - name: "breaking change"
    color: "ff0000"
    description: "Breaking change that requires migration"
  - name: "security"
    color: "ff0000"
    description: "Security related issue"
  - name: "performance"
    color: "ffa500"
    description: "Performance related issue"
  - name: "accessibility"
    color: "00ff00"
    description: "Accessibility related issue"
  - name: "mobile"
    color: "1d76db"
    description: "Mobile specific issue"
  - name: "desktop"
    color: "1d76db"
    description: "Desktop specific issue"

  # Maintenance labels
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "maintenance"
    color: "0366d6"
    description: "Maintenance tasks"
  - name: "chore"
    color: "0366d6"
    description: "Chores and maintenance tasks"
