name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Chores'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🎨 Style'
    labels:
      - 'style'
      - 'ui'
      - 'ux'
  - title: '♻️ Refactor'
    labels:
      - 'refactor'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'testing'
template: |
  ## What's Changed
  $CHANGES

  ## 🔗 Links
  - [Full Changelog](https://github.com/treyschmitt/artomate/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
  - [GitHub Release](https://github.com/treyschmitt/artomate/releases/tag/$RESOLVED_VERSION)

  ## 📦 Installation
  ```bash
  npm install artomate@$RESOLVED_VERSION
  ```

  ## 🚀 Quick Start
  ```bash
  git clone https://github.com/treyschmitt/artomate.git
  cd artomate
  npm install
  npm run dev
  ```

  ---
  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*
